### ISSUE TITLE
Not compatible with JDK 1.6

### ISSUE THREAD

**Issue by pkrish** [awslabs/amazon-sqs-java-messaging-lib#3]
When I change the target in the pom.xml to 1.6 I get the following error.

```
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
An unknown compilation problem occurred

at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:909)
at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
... 19 more
```

**Comment by kuba-aws** [comment]
Library supports Java 7 or later.
